version: "3.8"

services:
    container:
        image: "kohirens/circleci-aws-iac-tf:${BUILD_VER:-dev}"
        build:
            dockerfile: "Dockerfile"
            context: "."
            target: "dev"
        tty: true
